version: "3.8"
services:
  sub:
    build:
      context: ./sub
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true  # Required for accessing video devices
    restart: always
    container_name: subscriber
